service: inventory-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-1
  stage: dev

  profile: Natish

  environment:
    NODE_ENV: production
    SERVICE_NAME: ${env:SERVICE_NAME}
    AWS_REGION: ${env:AWS_REGION}
    DYNAMODB_TABLE_NAME: ${env:DYNAMODB_TABLE_NAME}
    DYNAMODB_MOVEMENTS_TABLE_NAME: ${env:DYNAMODB_MOVEMENTS_TABLE_NAME}
    PRODUCT_SERVICE_URL: ${env:PRODUCT_SERVICE_URL}

functions:
  app:
    handler: lambda.handler
    memorySize: 512
    timeout: 30

    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

      - httpApi:
          path: /
          method: ANY
