service: analytics-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-1
  stage: dev

  profile: Natish   # Replace with your AWS CLI SSO profile name

  environment:
    NODE_ENV: production
    SERVICE_NAME: ${env:SERVICE_NAME}
    AWS_REGION: ${env:AWS_REGION}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    INTERNAL_SERVICE_KEY: ${env:INTERNAL_SERVICE_KEY}
    ORDER_SERVICE_URL: ${env:ORDER_SERVICE_URL}
    PRODUCT_SERVICE_URL: ${env:PRODUCT_SERVICE_URL}
    CATEGORY_SERVICE_URL: ${env:CATEGORY_SERVICE_URL}
    INVENTORY_SERVICE_URL: ${env:INVENTORY_SERVICE_URL}
    PAYMENT_SERVICE_URL: ${env:PAYMENT_SERVICE_URL}
    COUPON_SERVICE_URL: ${env:COUPON_SERVICE_URL}

functions:
  app:
    name: natish_analytics_service_lambda
    handler: lambda.handler
    memorySize: 512
    timeout: 30

    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

      - httpApi:
          path: /
          method: ANY
